name: cs7643-project
channels:
  - defaults
dependencies:
  - pip
  - python=3.10
  - pip:
      - tqdm
      - matplotlib
      - seaborn
      - numpy
      - pandas
      - pyyaml
      - pyzmq
      - scipy
      - torch==1.13.1
      - spacy==3.4.4
      - torchtext==0.14.1
      - transformers==4.27.4
      - opendatasets
      - nltk==3.8.1
      - Faker==18.4.0
      - evaluate
      # - rouge_score
